name: malay_portfolio
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_responsive_helper: ^1.0.2
  auto_size_text: ^3.0.0
  get_cli: ^1.8.4
  flutter_animator: ^3.2.2
  url_launcher: ^6.1.14


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: FiraCode
      fonts:
        - asset: assets/fonts/FiraCode-Regular.ttf
          weight: 400
        - asset: assets/fonts/FiraCode-Light.ttf
          weight: 300
        - asset: assets/fonts/FiraCode-Medium.ttf
          weight: 500
        - asset: assets/fonts/FiraCode-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/FiraCode-Bold.ttf
          weight: 700

    - family: BigShoulder
      fonts:
        - asset: assets/fonts/big_shoulder_display/BigShouldersDisplay-Bold.ttf
          weight: 700

    - family: Iceland
      fonts:
        - asset: assets/fonts/iceland/Iceland-Regular.ttf
          weight: 400

